config/routes.rb
Rails.application.routes.draw do

  resources :bank_billets

  root 'bank_billets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_billet.rb
class BankBillet < ApplicationRecord

end

app/models/bank_billets/services/create.rb
module BankBillets::Services
  class Create
    def call(billet_service_handler, params)
      bank_billet = billet_service_handler.create(params)

      bank_billet
    end
  end
end

app/models/bank_billets/services/destroy.rb
module BankBillets::Services
  class Destroy
    def call(billet_service_handler, external_billet_id)
      service_response = billet_service_handler.cancel(id: external_billet_id) 

      service_response
    end
  end
end

app/models/states.rb
class States
  OPTIONS = [
      ["Acre", "AC"],
      ["Alagoas", "AL"],
      ["Amapá", "AP"],
      ["Amazonas", "AM"],
      ["Bahia", "BA"],
      ["Ceará", "CE"],
      ["Distrito Federal", "DF"],
      ["Espírito Santo", "ES"],
      ["Goiás", "GO"],
      ["Maranhão", "MA"],
      ["Mato Grosso", "MT"],
      ["Mato Grosso do Sul", "MS"],
      ["Minas Gerais", "MG"],
      ["Pará", "PA"],
      ["Paraíba", "PB"],
      ["Paraná", "PR"],
      ["Pernambuco", "PE"],
      ["Piauí", "PI"],
      ["Rio de Janeiro", "RJ"],
      ["Rio Grande do Norte", "RN"],
      ["Rio Grande do Sul", "RS"],
      ["Rondônia", "RO"],
      ["Roraima", "RR"],
      ["Santa Catarina", "SC"],
      ["São Paulo", "SP"],
      ["Sergipe", "SE"],
      ["Tocantins", "TO"]
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_billets_controller.rb
class BankBilletsController < ActionController::Base
  layout 'application'
  require 'uri'
  require 'net/http'

  def index
    @bank_billets = BankBillet.all
  end

  def show

  end

  def new
    @states = States::OPTIONS
  end

  def create
    params.permit!

    bank_billet = BankBillets::Services::Create.new.call(BoletoSimples::BankBillet, params)

    permitted_params_with_external_id = permitted_params.merge(external_billet_id: bank_billet[:id])

    BankBillet.create(permitted_params_with_external_id) if bank_billet.response_errors.blank?

    redirect_to root_path
  end

  def destroy
    bank_billet = BankBillet.find(params[:id])

    service_response = BankBillets::Services::Destroy.new.call(BoletoSimples::BankBillet, bank_billet.external_billet_id)

    bank_billet.destroy! if service_response.response_errors.blank?

    redirect_to root_path
  end

  def edit
    @bank_billet = BankBillet.find(params[:id])
    @states = States::OPTIONS
  end

  def update 
    bank_billet = BankBillet.find(params[:id])
    bank_billet.update(permitted_params)
  end

  private

  def permitted_params
    params.permit(
      :description,
      :amount,
      :expire_at,
      :customer_zipcode,
      :customer_state,
      :customer_city_name,
      :customer_neighborhood,
      :customer_address,
      :customer_address_number,
      :customer_address_complement,
      :customer_cnpj_cpf,
      :customer_email,
      :customer_person_name,
      :customer_person_type,
      :customer_phone_number,
      :external_billet_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_billets/edit.html.erb
<%= turbo_frame_tag "bank_billets_menu", class:"flex flex-row self-center w-4/5" do %>
  <div class="flex flex-col border rounded  bg-gray-100 shadow-sm w-full self-center justify-center p-4 space-y-5 mb-2">
    <div class="flex flex-row w-full justify-between items-center">
      <div class=" rounded border  bg-white text-gray-600 border-gray-300 shadow-sm transition-all duration-100 font-bold text-sm px-2 py-1">Criar novo boleto</div>

      <%= link_to root_path do %>
        <div class="text-white rounded bg-red-500 hover:bg-red-600 transition-all duration-100 font-bold text-sm px-2 py-1">Voltar</div>
      <% end %>
    </div>

    <%= form_with(url: bank_billet_path, method: :patch, class: 'space-y-2') do |form| %>

      <div class="flex flex-row w-2/4 mb-4">
        <div class="flex flex-col h-8 space-y-1">
          <div class=" text-sm">Descrição</div>
          <%= form.text_field :description,value: @bank_billet.description , class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>
      <div class="">
        <%= form.submit "Editar Boleto", class:"mt-8 text-white rounded bg-green-500 hover:bg-green-600 transition-all duration-100 font-bold text-sm px-2 py-1" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/bank_billets/index.html.erb
<%= turbo_frame_tag "bank_billets_menu", class:"flex flex-row self-center w-4/5" do %>
  <div class="flex flex-col border rounded  bg-gray-100 shadow-sm w-full self-center justify-center p-4 space-y-5">
    <div class="flex flex-row w-full justify-between items-center">
      <div class=" rounded border text-gray-600 border-gray-300 bg-white shadow-sm transition-all duration-100 font-bold text-sm px-2 py-1">Meus Boletos</div>

      <%= link_to new_bank_billet_path do %>
        <div class="text-white rounded bg-green-500 hover:bg-green-600 transition-all duration-100 font-bold text-sm px-2 py-1">Criar Boleto</div>
      <% end %>
    </div>
    <% @bank_billets.each do |billet|%>
      <%= render Billet::Component.new(billet: billet) %>
    <% end %>
  </div>
<% end %>

app/views/bank_billets/new.html.erb
<%= turbo_frame_tag "bank_billets_menu", class:"flex flex-row self-center w-4/5" do %>
  <div class="flex flex-col border rounded  bg-gray-100 shadow-sm w-full self-center justify-center p-4 space-y-5 mb-2">
    <div class="flex flex-row w-full justify-between items-center">
      <div class=" rounded border  bg-white text-gray-600 border-gray-300 shadow-sm transition-all duration-100 font-bold text-sm px-2 py-1">Criar novo boleto</div>

      <%= link_to root_path do %>
        <div class="text-white rounded bg-red-500 hover:bg-red-600 transition-all duration-100 font-bold text-sm px-2 py-1">Voltar</div>
      <% end %>
    </div>

    <%= form_with(url: bank_billets_path, method: :post, class: 'space-y-2') do |form| %>
      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Descrição</div>
          <%= form.text_field :description, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Valor</div>
          <%= form.number_field :amount, step: '0.01', class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6", placeholder: "R$ 0,00" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Data de vencimento:</div>
          <%= form.date_field :expire_at, class: "py-3 px-8 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-full h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">CEP</div>
          <%= form.text_field :customer_zipcode, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 app mb-6 space-y-1 ">
          <div class=" text-sm">Estado</div>
          <%= form.select :customer_state, options_for_select(@states), {}, class: 'h-8 border w-52 text-xs border border-gray-300 rounded-md focus:outline-none focus:border-blue-500' %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Cidade</div>
          <%= form.text_field :customer_city_name, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Bairro</div>
          <%= form.text_field :customer_neighborhood, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Endereço do cliente</div>
          <%= form.text_field :customer_address, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Número</div>
          <%= form.text_field :customer_address_number, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Complemento</div>
          <%= form.text_field :customer_address_complement, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">CNPJ ou CPF</div>
          <%= form.text_field :customer_cnpj_cpf, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Email do Cliente</div>
          <%= form.text_field :customer_email, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Nome do cliente</div>
          <%= form.text_field :customer_person_name, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
          <%= form.hidden_field :customer_person_type, value: "individual"%>
        </div>
      </div>

      <div class="flex flex-row w-2/4">
        <div class="flex flex-col h-8 mb-4 space-y-1">
          <div class=" text-sm">Telefone do cliente</div>
          <%= form.text_field :customer_phone_number, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-400 w-3/4 h-6" %>
        </div>
      </div>

      <%= form.submit "Criar Boleto", class:"text-white rounded bg-green-500 hover:bg-green-600 transition-all duration-100 font-bold text-sm px-2 py-1" %>
    <% end %>
  </div>
<% end %>

app/views/bank_slips/index.html.erb
<%= turbo_frame_tag "bank_slips_menu", class:"flex flex-row self-center w-4/5" do %>
  <div class="flex flex-col border rounded  bg-gray-100 shadow-sm w-full self-center justify-center p-3 space-y-5">
    <div class="flex flex-row w-full justify-between items-center">
      <div class="">Meus boletos</div>
      <%= link_to new_bank_slip_path do %>
        <div class="text-white rounded bg-green-500 hover:bg-green-600 transition-all duration-100 font-bold text-sm px-2 py-1">Criar Boleto</div>
      <% end %>
    </div>
    <%= render Billet::Component.new %>
  </div>
<% end %>

app/views/bank_slips/new.html.erb
<%= turbo_frame_tag "bank_slips_menu", class:"flex flex-row self-center w-4/5" do %>
  <div class="flex flex-col border rounded  bg-gray-100 shadow-sm w-full self-center justify-center p-3 space-y-5 mb-2">
    <div class="">Criar novo boleto</div>

    <%= form_with(model: @bank_slip, url: bank_slips_path, method: :post, class: '') do |form| %>
      <div class="flex flex-row w-2/4">
        <div class="flex flex-col">
          <%= form.label :amount, class: "text-sm text-gray-600 mb-1" %>
          <%= form.text_field :amount, class: "p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500 w-2/4 h-10" %>
        </div>
      </div>
      <%= form.submit "Criar Boleto" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerador de Boletos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200 text-gray-600 ">
    <div class="flex flex-row w-full border bg-white p-3 shadow-sm font-bold">
      <%= link_to "Gerador de boletos", root_path %>
    </div>
    <main class=" container mx-auto mt-8 px-5 flex flex-col">
      <%= yield %>
    </main>
  </body>
</html>